### ISSUE TITLE
navigation on arc42.github.io/faq always opens new tab...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/faq#15]
strange behavior - does not occur when "jekyll serve" locally...

an issue with _config.yaml??

**Comment by rdmueller** [comment]
chrome shows me that all links have a target="_blank"
it seems that https://arc42.github.io/faq//assets/js/script.js adds it

**Comment by rdmueller** [comment]
ah! externe links bekommen das target="_blank". Und als extern wird alles angesehen, was zwei // in der URL hat (http://).
Wenn ich es richtig sehe, dann liegt tatsächlich eine Fehlkonfiguration vor, die URLs á la ""/faq//general/2015/01/05/q-a-5/" erzeugt
