### ISSUE TITLE
What comment system to use? pros and cons

### ISSUE THREAD

**Issue by gernotstarke** [arc42/faq#5]
Comments on every page - "disqus" is the best-known system:

PRO
* enabling comments without requiring readers to open issue on github.
* slack integration possible
* free to use
* add-free for open-source projects (afaik...)
 
CON:
* disqus is collecting information about users
* disqus comments are "owned" by disqus (maybe not thaaat bad, as we don't have many comments)

**Comment by rdmueller** [comment]
I would go with disqus simply because it is easy to integrate.

Some additional system: http://www.hongkiat.com/blog/3rdparty-comment-discuss-systems-reviewed/

**Comment by gernotstarke** [comment]
cons: 

- disqus comments are "owned" by disqus
- there's ugly advertisement displayed with disqus comments

 comments gehören disqus...

**Comment by gernotstarke** [comment]
I tried MUUT on the site - please have a look and meta-comment on it :-)

**Comment by gernotstarke** [comment]
it's VERY simple to switch out https://muut.com/arc42/#!/feed in favor of disqus...

I prefer the styling of muut... let's see what u think.

(currently we're in the 14 day free trial)

**Comment by rdmueller** [comment]
works fine...

**Comment by rdmueller** [comment]
I guess the free version will be ok?

**Comment by gernotstarke** [comment]
hope so...  can you add a comment, please?

**Comment by rdmueller** [comment]
already did it.
http://faq.arc42.org/questions/J-5/

**Comment by gernotstarke** [comment]
disqus has a (free) slack integration...

**Comment by rdmueller** [comment]
Is this a pro or a con?

**Comment by gernotstarke** [comment]
as I don't want to login to my muut.com account every day to watch for new comments, a slack integration is imho a **strong** pro argument...

I'll try it out later today...

**Comment by rdmueller** [comment]
I thought there will be email notifications...?

**Comment by gernotstarke** [comment]
Ich habe gestern KEINE Email von muut bekommen, als Du was daran gemacht hast...

**Comment by gernotstarke** [comment]
oh oh, I don't get disqus to work - although it did a few days ago... will stop trying for now, defer to "some time after christmas"

**Comment by gernotstarke** [comment]
so - disqus sollte jetzt gehen. Ich sehe KEINE Werbung, und bekomme via Slack Nachrichten, wenn neue Kommentare eintreffen...
