### ISSUE TITLE
images not found in public site

### ISSUE THREAD

**Issue by gernotstarke** [arc42/faq#6]
although I see them in local preview...

**Comment by rdmueller** [comment]
the url
https://arc42.github.io/assets/img/innoQ_logo_bw.png
has to be
https://arc42.github.io/faq/assets/img/innoQ_logo_bw.png

I'll fix that...

**Comment by gernotstarke** [comment]
so einfach isses leider nicht:
/faq/assets funktioniert NUR auf der arc42.github.io/faq Website, das geht bei "localhost" leider nicht... und alle anderen images funktionieren auch noch nicht... (z.B. auf der "examples"-page)
Scheinbar muss man in _config.yaml den url oder baseurl setzen UND in allen image-Verweisen pre-penden...

**Comment by rdmueller** [comment]
Ok. Localost: man muss wohl die baseurl mit in die definition reinbringen.
Examples hatte ich nicht gesehen.
Ich kuemmer mich drum.

**Comment by rdmueller** [comment]
ok. here is the github and local solution - prepend the baseurl:

{{ '/images/arc42ByExample-small.png' | prepend: site.baseurl }}

just tested it on the examples page and will now search for further images.
also tested local (yes, I now have jekyll in a virtual machine up and running :-)

will close this issue as soon as I have (hopefully) all images found :-)

**Comment by gernotstarke** [comment]
use atom editor, global-find ![

thanx a lot 
Gernot

**Comment by gernotstarke** [comment]
tried to streamline your solution... as we'll have dozens of images:

in _config.yaml

    ## imageurl set to url + baseurl, easier than the complex
    ## {{ url }}{{ url }}{{ '<filename>' | prepend: site.baseurl }}
    imageurl: http://localhost:4000
    # imageurl: http://arc42.github.io/faq/
    # imageurl: (for faq.arc42.org...)

when using image:

    ![WebSequenceDiagram example]({{ site.imageurl }}/images/faq/F-Tools/wsd-authentication-example.png){:width="50%"}

That requires only a single liquid expression instead of two...

any objections??

**Comment by rdmueller** [comment]
that's perfect!
